### PR TITLE
Add support for variable COLR tables using VarIndexBase and DeltaSetIndexMap

### PR DESCRIPTION
**Pull request by anthrotype**
Towards #53

Requires the ~~https://github.com/fonttools/fonttools/compare/wip-variable-colr?expand=1~~ branch of fonttools to work

EDIT: the branch is now called https://github.com/fonttools/fonttools/compare/variable-colr?expand=1 (without the "wip-")

### CODE REVIEW

**Comment by anthrotype** [comment]
oops, clicked the green button too soon 😅 
well, i'll mark it as a draft for it requies stuff that hasn't been merged in fonttools yet

**Comment by justvanrossum** [comment]
Thanks for getting this started! Much apreciated.

**Comment by justvanrossum** [comment]
Thanks! Are there any Variable COLRv1 test fonts around?

**Comment by justvanrossum** [comment]
> I suppose this PR needs tests to be added. I am not familiar with the test suite. Mind leaving that to you?

Absolutely. Thank you so much for the implementation!

**Comment by anthrotype** [comment]
if you want a really simple one you can cd in fontTools/Tests/varLib/data and run `fonttools varLib TestVariableCOLR.designspace` and you get a simple TestVariableCOLR-VF.ttf with two color glyphs glyph, A and B that do very simple things.
@drott is working on more test fonts in https://github.com/googlefonts/color-fonts/pull/102

**Comment by justvanrossum** [comment]
I added the fonttools test font + glyphs to the test suite. Can you briefly verify that the images in the expected output are as you expect them to be?

**Comment by anthrotype** [comment]
>  Can you briefly verify that the images in the expected output are as you expect them to be?

yes, they look correct, thanks!

**Review by justvanrossum — APPROVED** [review]
Fantastic! More test cases would be nice, but let's do that later.

**Pull request merged**
