### PR TITLE
Fixing #81: skew x-angle should go counter-clockwise

### LINKED ISSUE #81: Skew in x-direction is clockwise, not counter-clockwise
After @justvanrossum's [report on rotation angles](https://bugs.chromium.org/p/skia/issues/detail?id=13190), I was looking closer at Chromium's implementation and comparing. 

It seems that BlackRenderer's skew angle in x-direction works in a clockwise fashion, positive angles turn clockwise, not counter-clockwise. 

In skew along the y-axis, the angle seems to be correct.

If I am not mistaken: For example `glyph_more_samples_skew_25_0_center_0_0_cairo.png` and from the test suite,

glyph_more_samples_skew_25_0_center_0_0_cairo

and 

`glyph_more_samples_skew_25_0_center_500.0_500.0_cairo.png` 

glyph_more_samples_skew_25_0_center_500 0_500 0_cairo

should look more like

image

### PR DESCRIPTION
**Pull request by justvanrossum**
Fixes #81.

### CODE REVIEW

**Comment by justvanrossum** [comment]
I would be super grateful for your review of this, @drott!

**Comment by drott** [comment]
Yes, from a first look, this looks good to me - that's a similar change to what I did in Skia to fix the x-axis skew direction. I'll compare the bitmap results again to what I have locally and get back to you in more detail.

**Comment by drott** [comment]
LGTM, compare also my proposed Skia change in https://skia-review.googlesource.com/c/skia/+/529076.

image

FYI, there are two more skew test glyphs in 
```
        _paint_skew(0, 15, 0, 0, next(access_chars)),
        _paint_skew(0, 15, _UPEM / 2, _UPEM / 2, next(access_chars)),
```

I assume your test suite is running those, but because only x-direction skew was affected they did not need new baselines?

**Comment by drott** [comment]
The results from this PR now match what I get after https://skia-review.googlesource.com/c/skia/+/529076 (not landed yet).

**Comment by justvanrossum** [comment]
> I assume your test suite is running those, but because only x-direction skew was affected they did not need new baselines?

Correct.

**Pull request merged**
